---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./metrics-server/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
  - ./nvidia-gpu-operator/ks.yaml
  - ./reloader/ks.yaml
  - ./kube-vip/ks.yaml
