---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname prowlarr
  namespace: flux-system
spec:
  targetNamespace: media-services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/media-services/prowlarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: openebs
    # - name: volsync
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "2000"
      APP_GID: "2000"
      # VOLSYNC_CLAIM: prowlarr-config
