---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1l54r23dn9at4saageec03dcgvgew5e0xrzgrr7xx4pmpgxujkugshn2lmm"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1l54r23dn9at4saageec03dcgvgew5e0xrzgrr7xx4pmpgxujkugshn2lmm"
