apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:HCGjdHHgWrPU/qrebXBIaEy4dAruDxew3CPnUOnZZg422V1rSIpmcw==,iv:bRw2or5eCn4CzMmSb1w2FxzUpeX7Eoxi5MTc9TukMq4=,tag:3TaurLDXcOz+PYwhEsnj4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l54r23dn9at4saageec03dcgvgew5e0xrzgrr7xx4pmpgxujkugshn2lmm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadUtvWjIwMXhIaEZ3TVN0
            dXlCNmdMd2tVV0x0cStXNzdJclhzdkRDampzCnhnUGc4eGh5VkkzL3B6c2FsMWlm
            QUZPelB3NG5zZVB1STJFeXVncEtvUFUKLS0tIFlVdU1KRGRTRy9obUxYNnVmdndR
            K0pERGdNdHJRVk9VV0NVTUlMakc0V1kKycc3i+2na5gKHOEN8YC18vml/iHmhgPp
            uCQINPlycEO+GuqnxFCP/u0/Jhot0F2tHGZ502YB8mOSYRNG+QCyqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T23:57:26Z"
    mac: ENC[AES256_GCM,data:kmyKR1H2yQRBAeZDt6vctQ6uKtrREOZ50TrQyG2HDO+mmDKOLfRIUcOWAEkb5jjM+aLbKX5Y1JObHD4S3ndf6Cl4qvsHKlIEFn1EDwUjSO+IdSKtMufeUMUChrvQTVA9QPTjqwf3VoMl5Cu1CLo/WOMFhpy/EncZWUG0cSMs4Vw=,iv:8RUwTmUGHKyuZM0z/C/k3neaBLDI3kAqAbVcVUNLHbw=,tag:7VgQLVsvx1THGjO2wQ2y6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
