---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  #- ./calibre-web/ks.yaml
  #- ./maintainerr/ks.yaml
  #- ./piped/ks.yaml
  - ./plex/ks.yaml
  - ./sonarr/ks.yaml
  #- ./tautulli/ks.yaml
