apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RZYzLlw/wrj4ibyw3TbOOGFWCrEWI/sraWWV4ss/XYe7C+KG,iv:ADxBPuSBgfSBP2w44xn33dfCPnuiJ9b8V2Po4tm9CvY=,tag:x8XjoLKxhB5QFS/5QS1Y2w==,type:str]
    credentials.json: ENC[AES256_GCM,data:QPHVo30yJ3Lvr7b9v8JpIC3gMHDIWYxEclDP6Gjl36onLR3DVwaDUj5DiCKyxMv84/iFfOr9w4aIAcKpxeLbZpOaDcbp8FCwlIfdTDgbBb0uJkRKvYZ4/wa6zBGGX15aIvIWcYBG5Jdw0g5hNVQPNg4GCQgeYV0M7V095RU69cr7tl2uCENhI+rviPUd8NdSRbVkrk60+R1ZOkaylOPQ99nuQDFodUJG8u+jv5OSxA==,iv:x19QMn2YzTWtAs1rtVcRZdWv5vTHPzUH3/UL7kdARqo=,tag:kfOBH1o9XQCo0Mbs7OGePA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l54r23dn9at4saageec03dcgvgew5e0xrzgrr7xx4pmpgxujkugshn2lmm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMmtsczFlL2RkK01PQzcy
            R3VoZmJZdCtWdVk3T2RQOTBzcHVGTFhYSzNZClJndE5YTlprWFBEMHhzMk15UHZn
            WUtEc0gyOEp3bVYxV240bW1aUzM2TlkKLS0tIG1BSzJNNmFUZkR6b2ZzeVNoUVZr
            c1FLY2lwaFE5UmxDOExtVnRMYmRwL0EKqEjjpoH8xIxSkH2vM31yrKo1VNfUQtEC
            NPZE1zBcKLL1ZJBe3OY0vBfxU6EUDeZ/gRxU2gDhqErSFGsTQk2BlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-05T23:57:27Z"
    mac: ENC[AES256_GCM,data:Y5UcxYNjFirVhWaPygUJXrdNSA3o3yb8WlOL+xMGCmdSActOvW72wRm5RiCFGDmJ7rSXZorYKHvLAmgjj4IB9n/E8A+TRgc79l6qj0S1Svvqd4nsnOynbURSRHLslRStzAER9id8NaCuL35ZEw1YRR10UsgRS0SPkgtz+6ueS3k=,iv:U9YF2wrzEEmFUs/yhRZs8sehmKD7OMMXfEUNxMXZ58c=,tag:9l1xYxjK+J8URqgHsfcg/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
